### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Scrum**
## Proposed Changes

Describe the big picture of your changes here to communicate to the maintainers
why we should accept this pull request. If it fixes a bug or resolves a feature
request, be sure to link to that issue.

## Types of Changes

What types of changes does your code introduce
_Put an `x` in the boxes that apply_

- [ ] Bug (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature which changes existing functionality)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask. We're here to
help! This is a reminder of what we are going to look for before merging your
code._

- [x] I have read the [CONTRIBUTING](/CONTRIBUTING.md) guide
- [ ] Lint and unit tests pass with my changes
- [ ] I have added tests that prove my fix is effective/works
- [x] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes are merged and published in downstream modules

## Further Comments

If this is a large or complex change, kick off the discussion by explaining why
you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Scrum** [comment]
@michael-ciniawsky ping

**Comment by michael-ciniawsky** [comment]
I'm not in favour of this change, I'm still uncertain how post-sequence works in terms of usability, please open an issue at `posthml-load-config/postcss-load-config` to discuss  a possible sequencing logic first, also if you want to have one config file for a project using PostHTML && PostCSS, why not build upon posthtml-load-config/postcss-load-config + your `project.config.js` file wrapping the logic of those to?

**Comment by Scrum** [comment]
Why such a set of plug-ins if you can use one universal for different processors ? And [post-config@0.0.4-alpha](https://github.com/post-org/post-config/tree/v0.0.4-alpha) now returns the full set of configuration for plugins and the processor itself.

package.json
```json
"name": "my-post-config",
"devDependencies": {
  "autoprefixer": "6.5.4",
  "cssnano": "3.9.1",
  "postcss-modules": "0.5.2"
},
"postcss": {
    "from": "test",
    "to": "./",
    "modules": {
      "generateScopedName": "[name]__[local]___[hash:base64:5]"
    },
    "autoprefixer": {
      "browsers": ["last 2 versions"]
    }
}
```

index.js
```js
import postConfig from 'post-config'

console.log(postConfig().postcss) => return {
  "from": "test",
  "to": "./",
  "plugins": {
    "postcss-modules": {
      "generateScopedName": "[name]__[local]___[hash:base64:5]"
    },
    "cssnano": {},
    "autoprefixer": {
      "browsers": ["last 2 versions"]
    }
  }
}
```

**Comment by michael-ciniawsky** [comment]
Why must the processor be included?

**Comment by Scrum** [comment]
```js
import posthtml from 'posthtml';
import postcss from 'postcss';
import postConfig from 'post-config';

const config = postConfig();

postcss().process(css, config.postcss).css
posthtml().process(html, config.posthtml).html
```
Unsupported options will be ignored by the process

**Pull request closed without merging**
